#!/bin/bash
echo "----------Empezando Test-------"
mkdir -p test/outputs
. ./config
echo $MYSHELL
for i in $(find test -name "*.test"); do # Not recommended, will break on whitespace
    echo ""
    cat "$i" | /bin/sh > test/outputs/test1
    cat "$i" | $MYSHELL > test/outputs/test2

    DIFF=$(diff $PWD/test/outputs/test1 $PWD/test/outputs/test2)

    if [ "$DIFF" != "" ];then
	echo "Test Fail"
    else
	echo "Test Ok"
    fi
done
